#!/bin/bash
rm ./work/Rvector.txt
#rm file_list.txt
rm concentration_listright.txt
rm wrong_list.txt
rm right_list.txt
#find SITE/ -name "tempR.txt" > file_list.txt
j=0

for DIR in `cat directory_list.txt`
do
	echo $DIR
        SITE="$(echo $DIR | cut -d/ -f7)"
        CHL="$(echo $DIR | cut -d/ -f9)"
        SM="$(echo $DIR | cut -d/ -f11)"
        CDOM="$(echo $DIR | cut -d/ -f13)"
        DPF="$(echo $DIR | cut -d/ -f15)"
        echo $SITE $CHL $SM $CDOM $DPF

	directory="/home/jxc4005/HYDROLIGHT/EL5.2/SITE/"$SITE"/CHL/"$CHL"/SM/"$SM"/CDOM/"$CDOM"/DPF/"$DPF

	if [ " $(cat $DIR/ref/tempR.txt | wc -l)" -ne 120 ]
        then
                echo $DIR >> $PWD/wrong_list.txt
		echo Warning: $DIR not completed yet and resubmitted!
		
		input=$SITE".txt"
                cat $input | sed 's"site"'$SITE'"g' | sed 's"flaCH"'$CHL'"g' | sed 's"flaCD"'$CDOM'"g' | sed 's"flaSM"'$SM'"g' | sed 's"user_dpfCHL"'$DPF'"g' | sed 's"user_dpfTSS"'$DPF'"g'  > $directory/input.txt

                 cat ELRun.sh | sed 's"flag"'$directory'"g' > $directory/ELRun.sh
                 #sbatch --qos=cis-normal $directory/ELRun.sh
		 #sbatch --qos=cis-nopreempt $directory/ELRun.sh
                 #sbatch --qos schott --partition premium $directory/ELRun.sh
        	 sbatch --qos free  --partition work --mem=100 $directory/ELRun.sh
		 let j++
	else

                echo $DIR >> $PWD/right_list.txt
                cat $DIR/ref/tempR.txt >> $PWD/work/Rvector.txt
                echo $SITE $CHL $SM $CDOM $DPF>> $PWD/concentration_listright.txt
                #rm $directory/* 2> /dev/null
	fi
        let i++
        echo $i

done
echo Jobs completed correctly: $(cat ./right_list.txt|wc -l)
echo Jobs not completed and resubmitted: $j

if [ "$j" -ne 0 ]
then
	nohup nice ./monitor.sh > nohup.out &
else
	exit
fi
