#!/bin/bash
rm directory_list.txt
rm -r SITE/
rm concentration_list.txt
for SITE in `cat SITE_list.txt`
do
for CHL in `cat CHL_list.txt`
do
     	for SM in `cat SM_list.txt`
	do
		for CDOM in `cat CDOM_list.txt`
		do
			for DPF in `cat DPF_list.txt`
			do
			directory="/home/jxc4005/HYDROLIGHT/EL5.2/SITE/"$SITE"/CHL/"$CHL"/SM/"$SM"/CDOM/"$CDOM"/DPF/"$DPF	
 			mkdir -p $directory
			echo $directory
			echo $directory >> directory_list.txt
			echo $SITE $CHL $SM $CDOM $DPF>> concentration_list.txt	
			mkdir -p $directory/ref	
			
			let i++
			input=$SITE".txt"		
			cat $input | sed 's"site"'$SITE'"g' | sed 's"flaCH"'$CHL'"g' | sed 's"flaCD"'$CDOM'"g' | sed 's"flaSM"'$SM'"g' | sed 's"user_dpfCHL"'$DPF'"g' | sed 's"user_dpfTSS"'$DPF'"g'  > $directory/input.txt

  			cat ELRun.sh | sed 's"flag"'$directory'"g' > $directory/ELRun.sh
			#cp ./CommonInputs/* $directory/
			#sbatch --qos=cis-normal $directory/ELRun.sh
			#sbatch --qos free --partition work $directory/ELRun.sh
			sbatch --qos schott --partition premium $directory/ELRun.sh
			echo $i
			done
		done
	done
done
done 

nohup nice ./monitor.sh > nohup.out &
