#!/bin/bash
rm ./work/Rvector.txt
rm file_list.txt
rm concentration_listright.txt
rm wrong_list.txt
rm right_list.txt

for DIR in `cat directory_list.txt`
do
	echo $DIR
        SITE="$(echo $DIR | cut -d/ -f8)"
        DPFCHL="$(echo $DIR | cut -d/ -f10)"
        DPFTSS="$(echo $DIR | cut -d/ -f12)"
        echo $SITE $DPFCHL $DPFTSS
	directory="/home/jxc4005/HYDROLIGHT/EL5.2/dpfdet/SITE/"$SITE"/DPFCHL/"$DPFCHL"/DPFTSS/"$DPFTSS
	if [ " $(cat $DIR/ref/tempR.txt | wc -l)" -ne 120 ]
        then
                echo $DIR/ref/tempR.txt >> $PWD/wrong_list.txt
		echo Warning: $DIR/ref/tempR.txt not completed yet and resubmitted!
		
		input=$SITE".txt"
		cat $input| sed 's"site"'$SITE'"g' | sed 's"user_dpfCHL"'$DPFCHL'"g' | sed 's"user_dpfTSS"'$DPFTSS'"g' > $directory/input.txt
                cat ELRun.sh | sed 's"flag"'$directory'"g' > $directory/ELRun.sh
                #cp ./CommonInputs/* $directory/
                #sbatch --qos=cis-normal $directory/ELRun.sh
		#sbatch --qos=cis-nopreempt $directory/ELRun.sh
                #sbatch --qos schott --partition premium $directory/ELRun.sh
        	sbatch --qos free  --partition work --mem=12 $directory/ELRun.sh
		let j++
	else

                echo $DIR/ref/tempR.txt >> $PWD/right_list.txt
                cat $DIR/ref/tempR.txt >> $PWD/work/Rvector.txt
                echo $SITE $DPFCHL $DPFTSS>> $PWD/concentration_listright.txt
                #rm $directory/* 2> /dev/null
	fi
        let i++
        echo $i

done
echo Jobs completed correctly: $(cat ./right_list.txt|wc -l)
echo Jobs not completed and resubmitted: $j

if [ "$(cat ./wrong_list.txt|wc -l)" -ne 0 ]
then
        nohup nice ./monitor.sh > nohup.out &
else    
        exit    
fi
