#!/bin/bash
#rm directory_list.txt
#rm input_list.txt
#rm -r output/
		for DPFCHL in `cat dpf_listCHL.txt`
		do
			#for DPFTSS in `cat dpf_listTSS.txt`
			#do
				#directory="/home/jxc4005/HYDROLIGHT/EL5.2/dpfdet/output4/"$DPFCHL"/"$DPFTSS
				directory="/home/jxc4005/HYDROLIGHT/EL5.2/dpfdet/output/"$DPFCHL
 				mkdir -p $directory
				echo $directory
				echo $directory >> directory_listtxt
				#echo $DPFCHL $DPFTSS >> input_list.txt
				echo $DPFCHL >> input_list.txt
				mkdir -p $directory/ref
			
				let i++
				cat input.txt| sed 's"user_dpfCHL"'$DPFCHL'"g' | sed 's"user_dpfTSS"'$DPFTSS'"g' > $directory/input.txt
  				#cat input.txt| sed 's"user_dpfCHL"'$DPFCHL'"g' | sed 's"user_dpfTSS"'$DPFCHL'"g' > $directory/input.txt
					
				cat ELRun.sh | sed 's"flag"'$directory'"g' > $directory/ELRun.sh
				chmod 755 $directory/ELRun.sh
				#sbatch --qos=cis-normal $directory/ELRun.sh
				#sbatch --qos=cis-nopreempt $directory/ELRun.sh			
				sbatch --qos schott --partition premium --mem=1000 $directory/ELRun.sh		
				echo $i
			#done
		done

nohup nice ./monitor.sh > nohup.out &
